---

- name: delete local charts from /tmp/sdcore-helm-charts/
  file:
    path: /tmp/sdcore-helm-charts/
    state: absent
  when: inventory_hostname in groups['master_nodes']  and core.helm.local_charts
  ignore_errors: yes

- name: remove iosmcn core
  kubernetes.core.helm:
    name: sd-core
    release_namespace: iosmcn
    state: absent
    wait: true
  when: inventory_hostname in groups['master_nodes']
  ignore_errors: yes

- name: remove 5gc chart repo
  kubernetes.core.helm_repository:
    name: aether
    state: absent
    repo_url: "https://charts.aetherproject.org"
  when: inventory_hostname in groups['master_nodes']
  ignore_errors: yes

- name: waiting for iosmcn pods to terminate
  shell: |
    kubectl wait -n iosmcn --for=delete --all=true -l app!=ue pod --timeout=180s
  when: inventory_hostname in groups['master_nodes']
  ignore_errors: yes

- name: delete namespace iosmcn
  shell: |
    kubectl delete namespace iosmcn
  when: inventory_hostname in groups['master_nodes']
  ignore_errors: yes

